ndt2:
# Publish all joint states -----------------------------------
  joint_state_controller:
   type: joint_state_controller/JointStateController
   publish_rate: 50
  tilt_motor_1:
   type: effort_controllers/JointPositionController
   joint: tilt_motor_1
   pid: {p: 10.0, i: 0.001, d: 0.01}
  tilt_motor_2:
   type: effort_controllers/JointPositionController
   joint: tilt_motor_2
   pid: {p: 10.0, i: 0.001, d: 0.01}
  tilt_motor_3:
   type: effort_controllers/JointPositionController
   joint: tilt_motor_3
   pid: {p: 10.0, i: 0.001, d: 0.01}
  tilt_motor_4:
   type: effort_controllers/JointPositionController
   joint: tilt_motor_4
   pid: {p: 10.0, i: 0.001, d: 0.01}
