tilt:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  tilt_rotor_0_joint_controller:
    type: position_controllers/JointPositionController
    joint: tilt_rotor_0_joint
    pid: {p: 10.0, i: 0.001, d: 0.01}
  tilt_rotor_1_joint_controller:
    type: position_controllers/JointPositionController
    joint: tilt_rotor_1_joint
    pid: {p: 10.0, i: 0.001, d: 0.01}
  tilt_rotor_2_joint_controller:
    type: position_controllers/JointPositionController
    joint: tilt_rotor_2_joint
    pid: {p: 10.0, i: 0.001, d: 0.01}
  tilt_rotor_3_joint_controller:
    type: position_controllers/JointPositionController
    joint: tilt_rotor_3_joint
    pid: {p: 10.0, i: 0.001, d: 0.01}
